@echo off
echo 🔄 Restarting F: Drive ESQs Platform...
taskkill /F /IM node.exe 2>nul
echo 📁 Switching to F: drive...
F:
cd "ESQs-Platform-MOBILE-ONLINE"
echo 📋 Copying updated server files...
copy "C:\Users\EBPC\ESQs Workspace\esqs-platform\backend-server.js" "backend-server.js" /Y
echo 🚀 Starting ESQs Platform from F: drive...
npm start
